import { Trip, ServiceProvider, User } from './types';

export const TEXT = {
  en: {
    home: 'Home',
    agita: 'AGITA',
    map: 'Map',
    chat: 'Chat',
    profile: 'Profile',
    sendPackage: 'Send Package',
    imTraveling: "I'm Traveling",
    servicesNearby: 'Services Nearby',
    viewAll: 'View All',
    recentTrips: 'Recent Trips',
    driver: 'Driver',
    sender: 'Sender',
    searchPlaceholder: 'Find services, drivers...',
    findTrip: 'Find a Trip',
    postTrip: 'Post a Trip',
    from: 'From (Origin)',
    to: 'To (Destination)',
    searchBtn: 'Search Trips',
    publishBtn: 'Publish Trip',
    analyzing: 'Analyzing Route...',
    availableTrips: 'Available Trips',
    contact: 'Contact',
    welcome: 'Connect with travelers and services in Angola.',
    getStarted: 'Get Started',
    heroTitle: 'AGITA your cargo',
    heroSubtitle: 'Send products to other provinces securely.',
    notificationTitle: 'Trip Match!',
    notificationBody: 'Someone is going to Benguela tomorrow.',
    aiLabel: 'KOMBO Tip',
    transportType: 'Transport',
    capacity: 'Capacity',
    price: 'Price',
    date: 'Date',
    time: 'Time',
    description: 'Description',
    categories: {
      all: 'All',
      driver: 'Driver',
      delivery: 'Delivery',
      barber: 'Barber',
      tech: 'Technician',
      beauty: 'Beauty',
      education: 'Education',
      events: 'Events'
    }
  },
  pt: {
    home: 'Início',
    agita: 'AGITA',
    map: 'Mapa',
    chat: 'Chat',
    profile: 'Perfil',
    sendPackage: 'Enviar Encomenda',
    imTraveling: 'Vou Viajar',
    servicesNearby: 'Serviços Próximos',
    viewAll: 'Ver Todos',
    recentTrips: 'Viagens Recentes',
    driver: 'Motorista',
    sender: 'Remetente',
    searchPlaceholder: 'Buscar serviços, kupapata...',
    findTrip: 'Buscar Boleia/Frete',
    postTrip: 'Publicar Viagem',
    from: 'De (Origem)',
    to: 'Para (Destino)',
    searchBtn: 'Buscar Viagens',
    publishBtn: 'Publicar Viagem',
    analyzing: 'Analisando Rota...',
    availableTrips: 'Viagens Disponíveis',
    contact: 'Contactar',
    welcome: 'Conecte-se com viajantes e serviços em Angola.',
    getStarted: 'Começar',
    heroTitle: 'AGITA a tua carga',
    heroSubtitle: 'Envia produtos para outras províncias com segurança.',
    notificationTitle: 'Nova Correspondência!',
    notificationBody: 'Alguém vai para Benguela amanhã.',
    aiLabel: 'Dica KOMBO',
    transportType: 'Transporte',
    capacity: 'Capacidade',
    price: 'Preço',
    date: 'Data',
    time: 'Hora',
    description: 'Descrição',
    categories: {
      all: 'Todos',
      driver: 'Motorista',
      delivery: 'Entregas',
      barber: 'Barbearia',
      tech: 'Técnico',
      beauty: 'Beleza',
      education: 'Aulas',
      events: 'Eventos'
    }
  }
};

// "Database" Users Table
export const MOCK_USERS: Record<string, User> = {
  'u1': { id: 'u1', name: 'Paulo Kassoma', avatar: 'https://picsum.photos/101/101', rating: 4.9, verified: true, location: 'Luanda', joinedDate: '2023-01-15', isPremium: true },
  'u2': { id: 'u2', name: 'Neuza Manuel', avatar: 'https://picsum.photos/102/102', rating: 4.7, verified: true, location: 'Lubango', joinedDate: '2023-03-20' },
  'u3': { id: 'u3', name: 'Carlos "Gordo"', avatar: 'https://picsum.photos/103/103', rating: 5.0, verified: false, location: 'Huambo', joinedDate: '2023-05-10' },
  'u4': { id: 'u4', name: 'Marta Rocha', avatar: 'https://picsum.photos/104/104', rating: 4.8, verified: true, location: 'Luanda', joinedDate: '2023-06-01' },
};

// "Database" Trips Table
export const MOCK_TRIPS: Trip[] = [
  {
    id: 't1',
    hostId: 'u1',
    host: MOCK_USERS['u1'],
    origin: 'Luanda (Maianga)',
    destination: 'Benguela',
    date: '2024-05-20',
    time: '06:00',
    transportType: 'truck',
    capacity: 200,
    capacityUnit: 'kg',
    pricePerUnit: 500,
    currency: 'Kz',
    description: 'Vou de Hilux, tenho espaço na caixa para caixas grandes e eletrodomésticos.',
    status: 'active'
  },
  {
    id: 't2',
    hostId: 'u2',
    host: MOCK_USERS['u2'],
    origin: 'Lubango',
    destination: 'Luanda',
    date: '2024-05-22',
    time: '14:00',
    transportType: 'plane',
    capacity: 5,
    capacityUnit: 'kg',
    pricePerUnit: 2000,
    currency: 'Kz',
    description: 'Levo documentos e encomendas pequenas na mala de mão. Viagem rápida TAAG.',
    status: 'active'
  },
  {
    id: 't3',
    hostId: 'u3',
    host: MOCK_USERS['u3'],
    origin: 'Huambo',
    destination: 'Luanda',
    date: '2024-05-23',
    time: '05:00',
    transportType: 'bus',
    capacity: 50,
    capacityUnit: 'kg',
    pricePerUnit: 300,
    currency: 'Kz',
    description: 'Macon. Posso levar sacos de batata ou milho.',
    status: 'active'
  }
];

// "Database" Services Table
export const MOCK_SERVICES: ServiceProvider[] = [
  {
    id: 's1',
    userId: 'u4',
    businessName: 'Tio João Express',
    category: 'driver',
    rating: 4.8,
    location: 'Mutamba, Luanda',
    basePrice: 500,
    priceUnit: 'corrida',
    coverImage: 'https://picsum.photos/200/200',
    distance: '0.8 km',
    tags: ['Kupapata', 'Rápido', 'Entrega'],
    description: 'Moto táxi rápido para fugir do engarrafamento da baixa.',
    available: true
  },
  {
    id: 's2',
    userId: 'u1',
    businessName: 'Frio Tech Angola',
    category: 'tech',
    rating: 4.9,
    location: 'Talatona, Luanda',
    basePrice: 15000,
    priceUnit: 'visita',
    coverImage: 'https://picsum.photos/201/201',
    distance: '5.0 km',
    tags: ['Climatização', 'Geradores', 'Manutenção'],
    description: 'Especialista em AC e Geradores. Peças originais.',
    available: true
  },
  {
    id: 's3',
    userId: 'u2',
    businessName: 'Marta Tranças & Wig',
    category: 'beauty',
    rating: 5.0,
    location: 'Kilamba, Luanda',
    basePrice: 8000,
    priceUnit: 'cabeça',
    coverImage: 'https://picsum.photos/202/202',
    distance: '12 km',
    tags: ['Beleza', 'Domicílio', 'Tranças'],
    description: 'Faço tranças ao domicílio no Kilamba e arredores.',
    available: false
  },
   {
    id: 's4',
    userId: 'u3',
    businessName: 'Mestre das Obras',
    category: 'tech',
    rating: 4.5,
    location: 'Viana, Luanda',
    basePrice: 5000,
    priceUnit: 'dia',
    coverImage: 'https://picsum.photos/203/203',
    distance: '15 km',
    tags: ['Pedreiro', 'Pintor', 'Canalização'],
    description: 'Construção civil e pequenas reparações.',
    available: true
  }
];